const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$$('.mode').forEach(b=>b.onclick=()=>{ $$('.mode').forEach(x=>x.classList.remove('active')); b.classList.add('active'); const m=b.dataset.mode; ['track','football','open'].forEach(x=>$('#'+x+'Panel')?.classList.toggle('hidden',x!==m)); });
$$('.presets button').forEach(b=>b.onclick=()=>{$$('.presets button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#gpsDistance').value=b.dataset.distance;});
function trackMark(d,l){d=Number(d);l=Number(l);const lap=400+2*Math.PI*1.22*(l-1);const pct=((d%lap)/lap)*100;return {lap,pct};}
$('#showTrack').onclick=()=>{const d=+$('#trackDistance').value,l=+$('#lane').value,r=trackMark(d,l);$('#trackResult').innerHTML=`<b>${d}m in Lane ${l}</b><br>Finish about <b>${r.pct.toFixed(1)}%</b> of the way around that lane from your start point. Lane ${l} lap estimate: ${r.lap.toFixed(1)}m.`};
$('#showFootball').onclick=()=>{const d=+$('#fbDistance').value||150;const start=+$('#startYard').value||0;const yards=d*1.09361;let end=(start+yards)%100;$('#footballResult').innerHTML=`<b>${d}m ≈ ${yards.toFixed(1)} yd</b><br>Starting at yard line ${start}, finish near yard line <b>${end.toFixed(1)}</b>.`};
let start=null,watch=null,last=0;const R=6371000,toRad=x=>x*Math.PI/180;function hav(a,b){const dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
$('#lockStart').onclick=async()=>{try{await window.mwNativePermission?.('location')}catch{}navigator.geolocation.getCurrentPosition(p=>{start={lat:p.coords.latitude,lon:p.coords.longitude};$('#gpsAccuracy').textContent=Math.round(p.coords.accuracy)+'m';$('#gpsBadge').textContent='START LOCKED';$('#startWalk').disabled=false;$('#gpsStatus').classList.remove('hidden');$('#gpsStatus').textContent='Start point locked. Tap Start Measuring.'},()=>alert('Location access is required for GPS mode.'),{enableHighAccuracy:true});}
$('#startWalk').onclick=()=>{if(!start)return;watch=navigator.geolocation.watchPosition(p=>{const cur={lat:p.coords.latitude,lon:p.coords.longitude};last=hav(start,cur);$('#gpsMeasured').textContent=last.toFixed(1)+'m';$('#gpsAccuracy').textContent=Math.round(p.coords.accuracy)+'m';$('#gpsBadge').textContent=last>=+$('#gpsDistance').value?'TARGET REACHED':'MEASURING';$('#gpsLiveStatus').textContent=last>=+$('#gpsDistance').value?'TARGET':'MEASURING';$('#gpsStatus').textContent=last>=+$('#gpsDistance').value?'Target distance reached. Mark this point.':'Keep walking to '+$('#gpsDistance').value+'m.'},{},{enableHighAccuracy:true,maximumAge:1000,timeout:10000})};
$('#resetGps').onclick=()=>{if(watch!=null)navigator.geolocation.clearWatch(watch);watch=null;start=null;last=0;$('#gpsMeasured').textContent='0.0 m';$('#gpsBadge').textContent='◎ STABILIZED GPS';$('#gpsLiveStatus').textContent='READY';$('#gpsStatus').classList.add('hidden');$('#startWalk').disabled=true};
function receiveMwPaceHandoff(){const q=new URLSearchParams(location.search);let p=null;try{p=JSON.parse(localStorage.getItem('mwPacerHandoff')||'null')}catch{};if(q.get('mw_handoff')==='1')p={distance:+q.get('distance'),reps:+q.get('reps'),targetTime:+q.get('target'),restSeconds:+q.get('rest'),week:+q.get('week'),day:+q.get('day'),title:q.get('title')||'MW Workout'};if(!p)return;$('#handoff').classList.remove('hidden');$('#handoffTitle').textContent=p.title||'MW Workout received';$('#handoffText').textContent=`Week ${p.week||'—'} Day ${p.day||'—'} • ${p.reps||'—'} reps • ${p.distance||'—'}m${p.targetTime?` • ${p.targetTime}s target`:''}`;if(p.distance){$('#trackDistance').value=p.distance;const fd=$('#fbDistance');if(fd&&[...fd.options].some(o=>+o.value===+p.distance))fd.value=p.distance;$('#gpsDistance').value=p.distance}}
receiveMwPaceHandoff();