const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let start=null,lastPoint=null,watch=null,total=0,targetHit=false,lastSpoken=0;
const R=6371000,toRad=x=>x*Math.PI/180;
function hav(a,b){const dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function target(){return Math.max(5,Number($('#gpsDistance').value)||100)}
function updateTarget(){const t=target();$('#targetReadout').textContent=t+'m';$$('.presets button').forEach(b=>b.classList.toggle('active',Number(b.dataset.distance)===t))}
function say(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=1;speechSynthesis.speak(u)}catch{}}
function buzz(){try{navigator.vibrate?.([180,90,260])}catch{}}
function setState(label,msg){$('#gpsLiveStatus').textContent=label;$('#gpsStatus').textContent=msg}
$$('.presets button').forEach(b=>b.onclick=()=>{$('#gpsDistance').value=b.dataset.distance;updateTarget()});
$('#gpsDistance').addEventListener('input',updateTarget);updateTarget();
$('#lockStart').onclick=async()=>{try{await window.mwNativePermission?.('location')}catch{};if(!navigator.geolocation){setState('UNAVAILABLE','Location services are not available on this device.');return}
 setState('LOCATING','Hold still while MW locks your starting point…');
 navigator.geolocation.getCurrentPosition(p=>{const acc=p.coords.accuracy||999;if(acc>25){$('#gpsAccuracy').textContent=Math.round(acc)+'m';$('#gpsBadge').textContent='△ WEAK GPS';setState('TRY AGAIN','GPS accuracy is too weak to lock a trustworthy start. Move into a more open area and try again.');return}
 start=lastPoint={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:acc,time:p.timestamp};total=0;targetHit=false;lastSpoken=0;$('#gpsMeasured').textContent='0.0 m';$('#distanceBar').style.width='0%';$('#gpsAccuracy').textContent=Math.round(acc)+'m';$('#gpsBadge').textContent=acc<=10?'◎ GPS READY':'◎ GPS FAIR';$('#startWalk').disabled=false;$('#saveMark').disabled=true;setState('START LOCKED','Start point locked. Walk the exact route you want measured, including curves or turns.');say('Start point locked.')},e=>setState('LOCATION NEEDED','Allow precise location access to use the Distance Pacer.'),{enableHighAccuracy:true,maximumAge:0,timeout:15000})};
$('#startWalk').onclick=()=>{if(!start||watch!=null)return;$('#startWalk').disabled=true;setState('MEASURING','Walk your route. MW is measuring the path you travel.');say('Measuring started.');
 watch=navigator.geolocation.watchPosition(p=>{const cur={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy||999,time:p.timestamp};$('#gpsAccuracy').textContent=Math.round(cur.accuracy)+'m';
 if(cur.accuracy>30){$('#gpsBadge').textContent='△ WEAK GPS';setState('GPS WEAK','Keep moving into a clearer area. Weak GPS points are not being counted.');return}
 if(lastPoint){const step=hav(lastPoint,cur),dt=Math.max(.001,(cur.time-lastPoint.time)/1000);const plausible=step<=Math.max(12,dt*12);const noiseFloor=Math.max(1.5,Math.min(4,cur.accuracy*.22));if(plausible&&step>=noiseFloor)total+=step}
 lastPoint=cur;const t=target(),pct=Math.min(100,total/t*100);$('#gpsMeasured').textContent=total.toFixed(1)+' m';$('#distanceBar').style.width=pct+'%';$('#gpsBadge').textContent=cur.accuracy<=10?'◎ GPS GOOD':'◎ GPS FAIR';
 const milestones=[.5,.75,.9,.95,1];for(const m of milestones){if(total>=t*m&&lastSpoken<m){lastSpoken=m;if(m<1)say(Math.round(t*m)+' meters');break}}
 if(total>=t&&!targetHit){targetHit=true;$('#saveMark').disabled=false;setState('TARGET REACHED','Target reached. Mark this finish point.');say(t+' meters. Target reached. Mark your finish.');buzz();try{navigator.geolocation.clearWatch(watch)}catch{}watch=null}else if(!targetHit)setState('MEASURING','Keep walking to '+t+'m. Curves and turns count toward your distance.')
 },e=>setState('GPS LOST','Location signal was interrupted. Hold position while GPS reconnects.'),{enableHighAccuracy:true,maximumAge:500,timeout:12000})};
function reset(){if(watch!=null)navigator.geolocation.clearWatch(watch);watch=null;start=lastPoint=null;total=0;targetHit=false;lastSpoken=0;try{speechSynthesis.cancel()}catch{};$('#gpsMeasured').textContent='0.0 m';$('#distanceBar').style.width='0%';$('#gpsAccuracy').textContent='—';$('#gpsBadge').textContent='◎ GPS CHECK';$('#gpsLiveStatus').textContent='READY';$('#gpsStatus').textContent='Stand still at your starting point and lock it when GPS is ready.';$('#startWalk').disabled=true;$('#saveMark').disabled=true}
$('#resetGps').onclick=reset;
$('#saveMark').onclick=()=>{if(!targetHit)return;localStorage.setItem('mwLastDistanceMark',JSON.stringify({target:target(),measured:Number(total.toFixed(1)),savedAt:new Date().toISOString()}));setState('MARK SAVED','Finish mark saved on this device. You can return to training or measure another distance.');say('Mark saved.')};
function receiveMwPaceHandoff(){const q=new URLSearchParams(location.search);let p=null;try{p=JSON.parse(localStorage.getItem('mwPacerHandoff')||'null')}catch{};if(q.get('mw_handoff')==='1')p={distance:+q.get('distance'),reps:+q.get('reps'),targetTime:+q.get('target'),restSeconds:+q.get('rest'),week:+q.get('week'),day:+q.get('day'),title:q.get('title')||'MW Workout'};if(!p)return;$('#handoff').classList.remove('hidden');$('#handoffTitle').textContent=p.title||'MW Workout received';$('#handoffText').textContent=`Week ${p.week||'—'} Day ${p.day||'—'} • ${p.reps||'—'} reps • ${p.distance||'—'}m${p.targetTime?` • ${p.targetTime}s target`:''}`;if(p.distance){$('#gpsDistance').value=p.distance;updateTarget()}}
receiveMwPaceHandoff();