-- MW Dynasty Founder OS v10
-- Seed the planned human organization. These are role plans, not claims that people are hired.

insert into public.founder_people_roles(
  title,department,role_type,status,reports_to,mission,responsibilities,scorecard,priority
)
select x.title,x.department,x.role_type,x.status,x.reports_to,x.mission,x.responsibilities::jsonb,x.scorecard::jsonb,x.priority
from (values
  ('Founder / CEO','Executive','founder','active',null,'Set MW Dynasty vision, approve consequential decisions, protect the brand and methodology, and allocate capital.','["Company vision","Final approvals","Capital allocation","Brand stewardship","Methodology authority"]','["Company health","Launch readiness","Cash discipline","Customer trust"]','urgent'),
  ('Chief Operating Officer','Executive / Operations','future_hire','planned','Founder / CEO','Own the operating cadence that turns MW strategy into reliable execution.','["Company operating rhythm","Cross-functional execution","SOP ownership","Service quality","Vendor coordination"]','["SLA attainment","Launch execution","Operating issue closure","Process coverage"]','high'),
  ('Chief Financial Officer','Finance','future_hire','planned','Founder / CEO','Own financial planning, reporting, cash discipline, pricing analysis, and business controls.','["Budgeting","Cash planning","Unit economics","Financial reporting","Pricing support"]','["Cash runway","Budget variance","Gross margin","MRR quality","Close timeliness"]','normal'),
  ('Bookkeeper / Accounting Specialist','Finance','future_hire','planned','Chief Financial Officer','Maintain accurate books, reconciliations, expense classification, and close support.','["Bookkeeping","Reconciliations","Expense coding","Monthly close support","Vendor records"]','["Unreconciled items","Close completion","Classification accuracy"]','high'),
  ('Chief Technology Officer','Technology','future_hire','planned','Founder / CEO','Own technical architecture, reliability, security, release quality, and engineering execution.','["Architecture","Engineering leadership","Security","Reliability","Technical roadmap"]','["Uptime","Release quality","Security findings","Engineering throughput"]','high'),
  ('Full-Stack / Platform Engineer','Technology','future_hire','planned','Chief Technology Officer','Build and maintain the MW web platform, APIs, billing integrations, and operational tooling.','["Frontend","Backend APIs","Supabase","Stripe","Observability"]','["Defect escape rate","Cycle time","Platform reliability"]','normal'),
  ('iOS Engineer','Technology','future_hire','planned','Chief Technology Officer','Own native iPhone quality, StoreKit, TestFlight, App Store delivery, and native integrations.','["Swift/WebView shell","StoreKit","TestFlight","App Store releases","Native diagnostics"]','["Crash-free sessions","Purchase success","Release lead time"]','normal'),
  ('QA / Release Engineer','Technology','future_hire','planned','Chief Technology Officer','Own regression testing, release gates, TestFlight validation, and production release evidence.','["Test plans","Regression QA","Release gates","TestFlight validation","Incident reproduction"]','["Release pass rate","Escaped defects","Time to reproduce","Gate evidence completeness"]','high'),
  ('Security & Privacy Lead','Technology / Risk','future_hire','planned','Chief Technology Officer','Protect customer data, access controls, secrets, authentication, and privacy operations.','["Access reviews","RLS/RPC reviews","Secret handling","Security incidents","Privacy controls"]','["Open high-risk findings","Time to remediate","Access exceptions","Incident count"]','high'),
  ('Chief Product Officer','Product','future_hire','planned','Founder / CEO','Own product strategy across Athlete, Coach, Founder, website, and future experiences.','["Product roadmap","User experience","Prioritization","Product analytics","Research"]','["Activation","Retention","Feature adoption","Roadmap delivery"]','normal'),
  ('Product Manager','Product','future_hire','planned','Chief Product Officer','Translate customer and business needs into clear product requirements and release priorities.','["Requirements","Backlog","Acceptance criteria","Customer feedback","Release coordination"]','["Cycle time","Adoption","Requirement quality","Backlog health"]','normal'),
  ('Chief Marketing Officer / Head of Growth','Marketing','future_hire','planned','Founder / CEO','Build the MW brand, acquisition engine, campaigns, content strategy, and conversion system.','["Growth strategy","Campaigns","Brand","Content strategy","Acquisition analytics"]','["Qualified traffic","CAC","Signup conversion","Campaign ROI"]','normal'),
  ('Creative / Content Lead','Marketing','future_hire','planned','Chief Marketing Officer / Head of Growth','Create premium MW creative, educational marketing content, and campaign assets.','["Creative direction","Video/content","Campaign assets","Brand consistency","Content calendar"]','["Asset throughput","Engagement","Brand consistency","Content conversion"]','normal'),
  ('Social / Media Specialist','Marketing','future_hire','planned','Creative / Content Lead','Operate social channels, community content, short-form media, and performance reporting.','["Social publishing","Community engagement","Short-form content","Channel analytics"]','["Engagement","Follower quality","Traffic","Lead contribution"]','low'),
  ('Chief Revenue Officer / Head of Sales','Sales','future_hire','planned','Founder / CEO','Build predictable revenue through Coach, school, club, and partnership sales.','["Sales strategy","Pipeline","Partnerships","Forecasting","Sales process"]','["Pipeline value","Win rate","Sales cycle","New MRR"]','normal'),
  ('School & Club Partnerships Manager','Sales','future_hire','planned','Chief Revenue Officer / Head of Sales','Develop relationships with schools, clubs, teams, and coaching organizations.','["Prospecting","Partnership discovery","Demos","Proposals","Account handoff"]','["Qualified organizations","Meetings","Proposals","Won partnerships"]','normal'),
  ('Sales Representative','Sales','future_hire','planned','Chief Revenue Officer / Head of Sales','Convert qualified Coach and organization opportunities into paying MW customers.','["Outbound","Follow-up","Demos","CRM hygiene","Closing support"]','["Qualified pipeline","Meetings","Conversion","New MRR"]','low'),
  ('Customer Success Manager','Customer Success','future_hire','planned','Chief Operating Officer','Own onboarding, adoption, retention, customer health, and proactive success for Athletes and Coaches.','["Onboarding","Customer health","Retention","Success reviews","Escalation coordination"]','["Activation","Retention","At-risk recovery","Time to value"]','high'),
  ('Customer Support Specialist','Customer Success','future_hire','planned','Customer Success Manager','Resolve day-to-day Athlete and Coach questions with speed, clarity, and consistent escalation.','["Ticket handling","Technical triage","Billing routing","Knowledge-base updates","Escalation"]','["First response time","Resolution time","Reopen rate","CSAT"]','high'),
  ('Performance Director','Performance / Coaching','future_hire','planned','Founder / CEO','Protect and operationalize the official MW sprint, strength, and coaching methodology.','["Methodology QA","Coach education","Program review","Performance standards","Knowledge governance"]','["Methodology consistency","Program QA","Coach adoption","Performance feedback quality"]','normal'),
  ('Sprint & Strength Content Specialist','Performance / Coaching','future_hire','planned','Performance Director','Maintain training education, drill instruction, strength content, and Sprint School assets under Founder-approved methodology.','["Sprint content","Strength content","Drill education","Content QA","Version support"]','["Content coverage","Accuracy","Update turnaround","Athlete comprehension"]','low'),
  ('Data & Analytics Lead','Data & Analytics','future_hire','planned','Founder / CEO','Turn MW product and business data into trusted definitions, dashboards, experiments, and decision support.','["KPI governance","Business intelligence","Cohorts","Funnel analysis","Data quality"]','["Metric consistency","Dashboard freshness","Data-quality issues","Decision adoption"]','normal'),
  ('Legal & Compliance Counsel','Legal / Compliance','future_hire','planned','Founder / CEO','Advise on contracts, privacy, platform compliance, App Store obligations, and business risk.','["Contracts","Privacy","Terms","App Store compliance","Risk review"]','["Open legal risks","Review turnaround","Compliance exceptions"]','normal'),
  ('People Operations / Recruiting Lead','People / HR','future_hire','planned','Chief Operating Officer','Build role clarity, hiring systems, onboarding, performance cadence, and people operations as MW grows.','["Recruiting","Onboarding","Role design","Performance cadence","People policies"]','["Time to fill","Onboarding completion","Role clarity","Retention"]','low')
) as x(title,department,role_type,status,reports_to,mission,responsibilities,scorecard,priority)
where not exists (
  select 1 from public.founder_people_roles r where lower(r.title)=lower(x.title)
);
