-- MW Dynasty Founder OS v1
-- Applied to production 2026-09-20. Safe to re-run.

create table if not exists public.founder_ai_agents (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  title text not null,
  department text not null,
  manager_code text,
  org_level text not null default 'specialist',
  mission text not null,
  responsibilities jsonb not null default '[]'::jsonb,
  kpis jsonb not null default '[]'::jsonb,
  authority_level text not null default 'analyze' check (authority_level in ('analyze','draft','execute_low_risk')),
  allowed_tools jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active','paused','retired')),
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.founder_ai_tasks (
  id uuid primary key default gen_random_uuid(),
  agent_code text references public.founder_ai_agents(code) on update cascade,
  title text not null, description text, department text,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'queued' check (status in ('queued','in_progress','waiting_approval','completed','blocked','cancelled')),
  source text not null default 'founder',
  requires_approval boolean not null default false,
  approval_status text check (approval_status is null or approval_status in ('pending','approved','rejected')),
  output_summary text, metadata jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(), due_at timestamptz, completed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.founder_approvals (
  id uuid primary key default gen_random_uuid(),
  category text not null, title text not null, description text,
  requested_action jsonb not null default '{}'::jsonb,
  risk_level text not null default 'medium' check (risk_level in ('low','medium','high','critical')),
  status text not null default 'pending' check (status in ('pending','approved','rejected','executed','cancelled')),
  requested_by_agent_code text references public.founder_ai_agents(code) on update cascade,
  reviewed_by uuid, review_note text, reviewed_at timestamptz, executed_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.founder_knowledge_proposals (
  id uuid primary key default gen_random_uuid(),
  title text not null, principle_text text not null,
  structured_rule jsonb not null default '{}'::jsonb, affected_areas jsonb not null default '[]'::jsonb,
  conflict_notes text, status text not null default 'draft' check (status in ('draft','review','approved','rejected','published')),
  version integer not null default 1, created_by uuid default auth.uid(), reviewed_by uuid,
  reviewed_at timestamptz, published_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.founder_crm_leads (
  id uuid primary key default gen_random_uuid(),
  name text, organization text, contact_email text,
  lead_type text not null default 'coach' check (lead_type in ('coach','school','club','partner','other')),
  stage text not null default 'new' check (stage in ('new','qualified','contacted','meeting','proposal','negotiation','won','lost')),
  source text, assigned_agent_code text references public.founder_ai_agents(code) on update cascade,
  estimated_monthly_value_cents integer not null default 0 check (estimated_monthly_value_cents >= 0),
  next_action text, notes text, created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.founder_marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null, channel text not null,
  status text not null default 'draft' check (status in ('draft','scheduled','active','paused','completed','cancelled')),
  audience text, objective text, budget_cents integer not null default 0 check (budget_cents >= 0),
  spend_cents integer not null default 0 check (spend_cents >= 0),
  leads integer not null default 0 check (leads >= 0), conversions integer not null default 0 check (conversions >= 0),
  starts_at timestamptz, ends_at timestamptz, metadata jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.founder_web_events (
  id bigint generated by default as identity primary key,
  session_key text not null, user_id uuid, event_type text not null, page_path text not null,
  audience text, source text, campaign text, referrer_host text, device_class text,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create index if not exists founder_ai_tasks_status_idx on public.founder_ai_tasks(status,priority,created_at desc);
create index if not exists founder_approvals_status_idx on public.founder_approvals(status,risk_level,created_at desc);
create index if not exists founder_knowledge_status_idx on public.founder_knowledge_proposals(status,updated_at desc);
create index if not exists founder_crm_stage_idx on public.founder_crm_leads(stage,updated_at desc);
create index if not exists founder_campaign_status_idx on public.founder_marketing_campaigns(status,updated_at desc);
create index if not exists founder_web_events_created_idx on public.founder_web_events(created_at desc);
create index if not exists founder_web_events_session_idx on public.founder_web_events(session_key,created_at desc);
create index if not exists founder_web_events_type_idx on public.founder_web_events(event_type,created_at desc);

alter table public.founder_ai_agents enable row level security;
alter table public.founder_ai_tasks enable row level security;
alter table public.founder_approvals enable row level security;
alter table public.founder_knowledge_proposals enable row level security;
alter table public.founder_crm_leads enable row level security;
alter table public.founder_marketing_campaigns enable row level security;
alter table public.founder_web_events enable row level security;

do $$
declare t text;
begin
  foreach t in array array['founder_ai_agents','founder_ai_tasks','founder_approvals','founder_knowledge_proposals','founder_crm_leads','founder_marketing_campaigns','founder_web_events']
  loop
    execute format('drop policy if exists %I on public.%I','mw_founder_select_'||t,t);
    execute format('create policy %I on public.%I for select to authenticated using (private.mw_is_founder())','mw_founder_select_'||t,t);
  end loop;
end $$;
drop policy if exists mw_founder_modify_ai_tasks on public.founder_ai_tasks;
create policy mw_founder_modify_ai_tasks on public.founder_ai_tasks for all to authenticated using (private.mw_is_founder()) with check (private.mw_is_founder());
drop policy if exists mw_founder_modify_approvals on public.founder_approvals;
create policy mw_founder_modify_approvals on public.founder_approvals for all to authenticated using (private.mw_is_founder()) with check (private.mw_is_founder());
drop policy if exists mw_founder_modify_knowledge on public.founder_knowledge_proposals;
create policy mw_founder_modify_knowledge on public.founder_knowledge_proposals for all to authenticated using (private.mw_is_founder()) with check (private.mw_is_founder());
drop policy if exists mw_founder_modify_crm on public.founder_crm_leads;
create policy mw_founder_modify_crm on public.founder_crm_leads for all to authenticated using (private.mw_is_founder()) with check (private.mw_is_founder());
drop policy if exists mw_founder_modify_campaigns on public.founder_marketing_campaigns;
create policy mw_founder_modify_campaigns on public.founder_marketing_campaigns for all to authenticated using (private.mw_is_founder()) with check (private.mw_is_founder());


insert into public.founder_ai_agents(code,name,title,department,manager_code,org_level,mission,responsibilities,kpis,authority_level,sort_order)
select code,name,title,department,manager_code,org_level,mission,responsibilities,kpis,authority_level,sort_order
from jsonb_to_recordset('[{"code":"chief_of_staff","name":"Chief of Staff AI","title":"Chief of Staff","department":"Executive Office","manager_code":null,"org_level":"executive","mission":"Turn Founder priorities into coordinated company execution.","responsibilities":["Prepare executive briefings","Route work to departments","Track cross-functional priorities","Escalate decisions requiring Founder approval"],"kpis":["Founder decision latency","Critical task completion","Cross-functional blockers"],"authority_level":"draft","sort_order":10},{"code":"cfo","name":"CFO AI","title":"Chief Financial Officer","department":"Finance","manager_code":null,"org_level":"executive","mission":"Protect cash, explain revenue, and keep financial decisions grounded in current MW data.","responsibilities":["Revenue reporting","Subscription economics","Cost monitoring","Financial scenarios"],"kpis":["MRR","Churn","Gross margin","Cash requirements"],"authority_level":"analyze","sort_order":20},{"code":"controller","name":"Controller AI","title":"Controller","department":"Finance","manager_code":"cfo","org_level":"director","mission":"Maintain clean management reporting and billing reconciliation.","responsibilities":["Reconcile Apple, Stripe, and MW records","Track billing exceptions","Prepare finance close checklist"],"kpis":["Billing mismatches","Close accuracy","Exception aging"],"authority_level":"analyze","sort_order":21},{"code":"revops_finance","name":"Revenue Operations AI","title":"Revenue Operations Manager","department":"Finance","manager_code":"cfo","org_level":"manager","mission":"Connect pricing, billing, sponsorship, and revenue performance.","responsibilities":["Plan mix analysis","Sponsorship economics","Upgrade and downgrade reporting"],"kpis":["ARPU","Plan mix","Sponsor utilization"],"authority_level":"analyze","sort_order":22},{"code":"coo","name":"COO AI","title":"Chief Operating Officer","department":"Operations","manager_code":null,"org_level":"executive","mission":"Keep MW Dynasty operating reliably across people, process, and customer delivery.","responsibilities":["Operating cadence","SOP ownership","Launch readiness","Cross-team execution"],"kpis":["Operational SLA","Blocked work","Launch readiness"],"authority_level":"draft","sort_order":30},{"code":"operations_director","name":"Operations Director AI","title":"Director of Operations","department":"Operations","manager_code":"coo","org_level":"director","mission":"Translate operating plans into repeatable systems.","responsibilities":["Workflow design","Quality control","Process audits"],"kpis":["Cycle time","Process errors","SOP coverage"],"authority_level":"draft","sort_order":31},{"code":"cto","name":"CTO AI","title":"Chief Technology Officer","department":"Technology","manager_code":null,"org_level":"executive","mission":"Protect technical quality, security, reliability, and release velocity.","responsibilities":["Architecture","Security posture","Release risk","Platform reliability"],"kpis":["Error rate","Release health","Security findings"],"authority_level":"analyze","sort_order":40},{"code":"engineering_director","name":"Engineering Director AI","title":"Director of Engineering","department":"Technology","manager_code":"cto","org_level":"director","mission":"Coordinate implementation, technical debt, and engineering standards.","responsibilities":["Engineering backlog","Code quality","Integration health"],"kpis":["Defect escape rate","Backlog age","Integration failures"],"authority_level":"draft","sort_order":41},{"code":"release_qa","name":"Release & QA AI","title":"Release / QA Manager","department":"Technology","manager_code":"engineering_director","org_level":"manager","mission":"Prevent bad releases and convert diagnostics into actionable fixes.","responsibilities":["TestFlight QA","Regression plans","Launch diagnostics","Release gates"],"kpis":["Crash-free sessions","Open release blockers","Regression pass rate"],"authority_level":"analyze","sort_order":42},{"code":"reliability","name":"Reliability AI","title":"Reliability Specialist","department":"Technology","manager_code":"engineering_director","org_level":"specialist","mission":"Watch API, billing, sync, and app reliability signals.","responsibilities":["Diagnostics triage","API failure review","Sync health","Incident summaries"],"kpis":["API failures","Sync failures","Incident recovery time"],"authority_level":"analyze","sort_order":43},{"code":"cpo","name":"CPO AI","title":"Chief Product Officer","department":"Product","manager_code":null,"org_level":"executive","mission":"Keep the product simple, valuable, and aligned with Athlete, Coach, and Founder needs.","responsibilities":["Roadmap","Feature prioritization","Product quality","User-flow simplification"],"kpis":["Activation","Feature adoption","Drop-off"],"authority_level":"draft","sort_order":50},{"code":"product_manager","name":"Product Manager AI","title":"Product Manager","department":"Product","manager_code":"cpo","org_level":"manager","mission":"Turn product goals and feedback into defined work.","responsibilities":["Requirements","Acceptance criteria","Prioritization","Feedback synthesis"],"kpis":["Feature completion","Rework","Adoption"],"authority_level":"draft","sort_order":51},{"code":"website_growth","name":"Website & Growth AI","title":"Website & Growth Manager","department":"Product","manager_code":"cpo","org_level":"manager","mission":"Own the public website funnel from first visit through account and payment.","responsibilities":["Website health","Conversion funnel","Landing-page analysis","CTA performance"],"kpis":["Visitor-to-signup","Signup-to-payment","Broken routes"],"authority_level":"analyze","sort_order":52},{"code":"cmo","name":"CMO AI","title":"Chief Marketing Officer","department":"Marketing","manager_code":null,"org_level":"executive","mission":"Build qualified awareness and demand without diluting the MW brand.","responsibilities":["Marketing strategy","Campaign portfolio","Brand consistency","Growth experiments"],"kpis":["Qualified traffic","CAC","Campaign conversion"],"authority_level":"draft","sort_order":60},{"code":"growth_marketing","name":"Growth Marketing AI","title":"Growth Marketing Manager","department":"Marketing","manager_code":"cmo","org_level":"manager","mission":"Run measurable acquisition experiments across channels.","responsibilities":["Campaign planning","Attribution","Funnel experiments"],"kpis":["Lead volume","Cost per lead","Conversion rate"],"authority_level":"draft","sort_order":61},{"code":"content_seo","name":"Content & SEO AI","title":"Content / SEO Specialist","department":"Marketing","manager_code":"growth_marketing","org_level":"specialist","mission":"Turn MW expertise into discoverable, useful content.","responsibilities":["SEO briefs","Content calendar","Search intent research"],"kpis":["Organic traffic","Qualified clicks","Content conversions"],"authority_level":"draft","sort_order":62},{"code":"creative_lead","name":"Creative AI","title":"Creative Lead","department":"Marketing","manager_code":"cmo","org_level":"manager","mission":"Protect premium MW visual and messaging consistency.","responsibilities":["Creative briefs","Campaign concepts","Brand QA"],"kpis":["Creative throughput","Brand consistency"],"authority_level":"draft","sort_order":63},{"code":"cro","name":"CRO AI","title":"Chief Revenue Officer","department":"Sales","manager_code":null,"org_level":"executive","mission":"Grow recurring revenue across athletes, coaches, schools, clubs, and partnerships.","responsibilities":["Sales strategy","Pipeline review","Pricing feedback","Revenue forecast"],"kpis":["Pipeline value","Win rate","Sales cycle"],"authority_level":"analyze","sort_order":70},{"code":"sales_director","name":"Sales Director AI","title":"Director of Sales","department":"Sales","manager_code":"cro","org_level":"director","mission":"Operate the sales pipeline and coach the virtual sales team.","responsibilities":["Pipeline stages","Follow-up discipline","Opportunity review"],"kpis":["Qualified pipeline","Stage velocity","Wins"],"authority_level":"draft","sort_order":71},{"code":"partnerships","name":"Partnerships AI","title":"Partnerships Manager","department":"Sales","manager_code":"sales_director","org_level":"manager","mission":"Develop school, club, team, and strategic partnerships.","responsibilities":["Partner research","Proposal preparation","Relationship plans"],"kpis":["Meetings","Partner pipeline","Closed partnerships"],"authority_level":"draft","sort_order":72},{"code":"sales_rep","name":"Sales Representative AI","title":"Sales Representative","department":"Sales","manager_code":"sales_director","org_level":"specialist","mission":"Support prospecting and disciplined follow-up.","responsibilities":["Lead research","Outreach drafts","CRM follow-up"],"kpis":["Qualified leads","Response rate","Meetings booked"],"authority_level":"draft","sort_order":73},{"code":"cco","name":"Customer Success AI","title":"Chief Customer Officer","department":"Customer Success","manager_code":null,"org_level":"executive","mission":"Keep Athletes and Coaches successful, supported, and retained.","responsibilities":["Customer health","Support escalation","Retention patterns"],"kpis":["Retention","Support SLA","Resolution quality"],"authority_level":"analyze","sort_order":80},{"code":"support_manager","name":"Support Manager AI","title":"Support Manager","department":"Customer Success","manager_code":"cco","org_level":"manager","mission":"Run support triage and escalation.","responsibilities":["Queue triage","Response drafts","Escalations","Root-cause grouping"],"kpis":["Time to first response","Resolution time","Reopen rate"],"authority_level":"draft","sort_order":81},{"code":"support_specialist","name":"Support Specialist AI","title":"Support Specialist","department":"Customer Success","manager_code":"support_manager","org_level":"specialist","mission":"Handle routine customer questions and prepare escalations.","responsibilities":["FAQ support","Account issue triage","Escalation notes"],"kpis":["Tickets resolved","Accuracy","Escalation quality"],"authority_level":"draft","sort_order":82},{"code":"performance_director","name":"Performance AI","title":"Director of Performance","department":"Performance / Coaching","manager_code":null,"org_level":"executive","mission":"Protect MW training quality and Founder-approved methodology.","responsibilities":["Methodology governance","Program consistency","Coach education quality"],"kpis":["Program consistency","Methodology conflicts","Education quality"],"authority_level":"analyze","sort_order":90},{"code":"methodology_manager","name":"Methodology AI","title":"Sprint Methodology Manager","department":"Performance / Coaching","manager_code":"performance_director","org_level":"manager","mission":"Structure Founder coaching principles into reviewable rules without changing them autonomously.","responsibilities":["Knowledge proposals","Conflict analysis","Affected-week mapping"],"kpis":["Proposal clarity","Conflicts caught","Founder approval accuracy"],"authority_level":"draft","sort_order":91},{"code":"education_specialist","name":"Sprint School AI","title":"Sprint School Education Specialist","department":"Performance / Coaching","manager_code":"performance_director","org_level":"specialist","mission":"Turn approved MW principles into clear Athlete and Coach education.","responsibilities":["Lesson structure","Education QA","Terminology consistency"],"kpis":["Lesson quality","Coverage","Consistency"],"authority_level":"draft","sort_order":92},{"code":"data_chief","name":"Data & Analytics AI","title":"Chief Data & Analytics Officer","department":"Data & Analytics","manager_code":null,"org_level":"executive","mission":"Turn MW data into trustworthy operating intelligence.","responsibilities":["Metric definitions","Executive analytics","Data quality","Experiment measurement"],"kpis":["Metric trust","Dashboard freshness","Data gaps"],"authority_level":"analyze","sort_order":100},{"code":"bi_analyst","name":"Business Intelligence AI","title":"Business Intelligence Analyst","department":"Data & Analytics","manager_code":"data_chief","org_level":"specialist","mission":"Build clear explanations of growth, revenue, retention, and usage.","responsibilities":["Dashboard analysis","Trend detection","Cohort reporting"],"kpis":["Insight quality","Report timeliness"],"authority_level":"analyze","sort_order":101},{"code":"legal_risk","name":"Legal & Risk AI","title":"Legal / Compliance / Risk Manager","department":"Legal / Compliance","manager_code":null,"org_level":"executive","mission":"Surface compliance, privacy, contract, and platform-risk issues for human review.","responsibilities":["Privacy review","Store policy review","Contract issue spotting","Risk register"],"kpis":["Open high-risk items","Policy readiness","Review turnaround"],"authority_level":"analyze","sort_order":110}]'::jsonb) as x(
 code text,name text,title text,department text,manager_code text,org_level text,mission text,
 responsibilities jsonb,kpis jsonb,authority_level text,sort_order integer
)
on conflict (code) do update set
 name=excluded.name,title=excluded.title,department=excluded.department,manager_code=excluded.manager_code,
 org_level=excluded.org_level,mission=excluded.mission,responsibilities=excluded.responsibilities,
 kpis=excluded.kpis,authority_level=excluded.authority_level,sort_order=excluded.sort_order,updated_at=now();

CREATE OR REPLACE FUNCTION public.mw_founder_os_snapshot(p_section text DEFAULT 'overview'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_section text := lower(trim(coalesce(p_section,'overview')));
  v_out jsonb;
begin
  if auth.uid() is null or not private.mw_is_founder() then
    raise exception 'Founder / Owner access required' using errcode='42501';
  end if;

  if v_section='overview' then
    select jsonb_build_object(
      'generated_at',now(),
      'metrics',jsonb_build_object(
        'athletes_total',(select count(*) from public.profiles p where p.role::text='athlete'),
        'athletes_active',(select count(*) from public.profiles p where p.role::text='athlete' and p.account_status::text='active'),
        'coaches_total',(select count(*) from public.profiles p where p.role::text='coach'),
        'coaches_active',(select count(*) from public.coach_access_entitlements e join public.profiles p on p.user_id=e.coach_user_id where p.role::text='coach' and e.status='active'),
        'applications_need_review',(select count(*) from public.coach_access_applications a where a.verification_status='needs_review' and a.status='pending'),
        'active_base_subscriptions',(select count(*) from public.billing_subscriptions b where b.status in ('active','trialing','cancel_at_period_end') and (b.current_period_end is null or b.current_period_end>now())),
        'sponsored_seats_active',(select count(*) from public.coach_sponsor_seats s where s.status in ('invited','claimed','active','scheduled_to_end')),
        'open_support',(
          (select count(*) from public.support_requests s where coalesce(s.status,'open') not in ('closed','resolved'))
          +(select count(*) from public.public_support_requests s where coalesce(s.status,'open') not in ('closed','resolved'))
        ),
        'diagnostic_errors_24h',(select count(*) from public.launch_diagnostics d where d.severity='error' and d.created_at>now()-interval '24 hours'),
        'new_accounts_30d',(select count(*) from public.profiles p where p.created_at>now()-interval '30 days'),
        'web_sessions_30d',(select count(distinct w.session_key) from public.founder_web_events w where w.created_at>now()-interval '30 days'),
        'estimated_mrr_cents',
          coalesce((
            select sum(mp.monthly_price_cents)
            from public.billing_subscriptions b
            join public.membership_plans mp on mp.plan_code=b.plan_code
            where b.billing_type='individual'
              and b.status in ('active','trialing','cancel_at_period_end')
              and (b.current_period_end is null or b.current_period_end>now())
          ),0)
          +coalesce((
            select sum(greatest(p.requested_seats,0)*greatest(p.seat_price_cents,0))
            from public.coach_sponsorship_packages p
            where p.status in ('active','cancel_at_period_end')
              and (p.current_period_end is null or p.current_period_end>now())
          ),0)
      ),
      'needs_attention',
        coalesce((
          select jsonb_agg(x.item order by x.rank,x.created_at desc)
          from (
            select 1 rank,a.created_at,
              jsonb_build_object('type','coach_application','severity','high','title','Coach application needs review','detail',concat_ws(' · ',trim(coalesce(a.first_name,'')||' '||coalesce(a.last_name,'')),a.organization),'id',a.id,'action','applications') item
            from public.coach_access_applications a
            where a.verification_status='needs_review' and a.status='pending'
            union all
            select 1,b.updated_at,
              jsonb_build_object('type','billing','severity','high','title','Billing needs attention','detail',concat(coalesce(b.plan_code,'membership'),' · ',coalesce(b.status,'unknown')),'id',b.id,'action','revenue')
            from public.billing_subscriptions b
            where b.status in ('past_due','unpaid','incomplete','incomplete_expired')
            union all
            select 2,s.created_at,
              jsonb_build_object('type','support','severity','medium','title','Support request is still open','detail',coalesce(s.category,'Support request'),'id',s.id,'action','support')
            from public.support_requests s
            where coalesce(s.status,'open') not in ('closed','resolved') and s.created_at<now()-interval '24 hours'
            union all
            select 2,s.created_at,
              jsonb_build_object('type','public_support','severity','medium','title','Public support request is still open','detail',coalesce(s.category,'Website support request'),'id',s.id,'action','support')
            from public.public_support_requests s
            where coalesce(s.status,'open') not in ('closed','resolved') and s.created_at<now()-interval '24 hours'
            union all
            select 2,d.created_at,
              jsonb_build_object('type','diagnostic','severity','medium','title','Launch diagnostic error','detail',concat_ws(' · ',d.surface,d.code,d.route),'id',d.id,'action','system')
            from public.launch_diagnostics d
            where d.severity='error' and d.created_at>now()-interval '24 hours'
            union all
            select 2,r.requested_at,
              jsonb_build_object('type','deletion','severity','medium','title','Account deletion request pending','detail','Account deletion workflow requires review','id',r.id,'action','support')
            from public.account_deletion_requests r
            where r.status not in ('completed','cancelled')
            union all
            select 3,p.updated_at,
              jsonb_build_object('type','sponsorship','severity','low','title','Sponsored seats fully allocated','detail',concat(coalesce(pr.first_name,'Coach'),' · ',p.requested_seats,' seats'),'id',p.id,'action','sponsorships')
            from public.coach_sponsorship_packages p
            left join public.profiles pr on pr.user_id=p.coach_user_id
            where p.status in ('active','cancel_at_period_end')
              and p.requested_seats>0
              and not exists(select 1 from public.coach_sponsor_seats s where s.package_id=p.id and s.status='available')
          ) x
        ),'[]'::jsonb),
      'recent_activity',
        coalesce((
          select jsonb_agg(z.item order by z.created_at desc)
          from (
            select a.created_at,
              jsonb_build_object('kind','coach_application','title',concat_ws(' ',a.first_name,a.last_name),'detail',coalesce(a.verification_status,a.status),'at',a.created_at) item
            from public.coach_access_applications a
            order by a.created_at desc limit 8
          ) z
        ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='coaches' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce(jsonb_agg(jsonb_build_object(
        'user_id',p.user_id,
        'name',trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')),
        'organization',p.coach_organization,
        'title',p.coach_title,
        'account_status',p.account_status::text,
        'tier',e.access_tier,
        'access_source',e.access_source,
        'plan_code',b.plan_code,
        'billing_status',b.status,
        'provider',b.provider,
        'period_end',b.current_period_end,
        'cancel_at_period_end',b.cancel_at_period_end,
        'athletes',coalesce(ca.athletes,0),
        'sponsor_total',coalesce(sp.requested_seats,0),
        'sponsor_used',coalesce(sp.used_seats,0),
        'application_status',app.verification_status,
        'application_created_at',app.created_at,
        'created_at',p.created_at
      ) order by p.created_at desc),'[]'::jsonb)
    ) into v_out
    from public.profiles p
    left join lateral (
      select e.* from public.coach_access_entitlements e
      where e.coach_user_id=p.user_id and e.status='active'
      order by e.updated_at desc limit 1
    ) e on true
    left join lateral (
      select b.* from public.billing_subscriptions b
      where b.beneficiary_user_id=p.user_id and b.audience='coach'
      order by b.updated_at desc limit 1
    ) b on true
    left join lateral (
      select count(*) athletes from public.coach_assignments x
      where x.coach_user_id=p.user_id and x.status::text='active'
    ) ca on true
    left join lateral (
      select s.requested_seats,
             count(seat.id) filter (where seat.status in ('invited','claimed','active','scheduled_to_end')) used_seats
      from public.coach_sponsorship_packages s
      left join public.coach_sponsor_seats seat on seat.package_id=s.id
      where s.coach_user_id=p.user_id and s.status in ('active','cancel_at_period_end')
      group by s.id,s.requested_seats,s.created_at
      order by s.created_at desc limit 1
    ) sp on true
    left join lateral (
      select a.verification_status,a.created_at from public.coach_access_applications a
      where a.coach_user_id=p.user_id or lower(trim(a.email))=(select lower(trim(u.email)) from auth.users u where u.id=p.user_id)
      order by a.created_at desc limit 1
    ) app on true
    where p.role::text='coach';

  elsif v_section='athletes' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce(jsonb_agg(jsonb_build_object(
        'athlete_id',a.id,
        'user_id',a.user_id,
        'name',trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')),
        'account_status',p.account_status::text,
        'events',a.selected_events,
        'experience_level',a.experience_level,
        'current_week',ps.current_week,
        'current_day',ps.current_day,
        'program_status',ps.program_status::text,
        'track_tier',ps.track_tier,
        'strength_tier',ps.strength_tier,
        'assessment_complete',ps.onboarding_assessment_completed_at is not null,
        'membership_plan',me.plan_code,
        'membership_status',me.status,
        'membership_source',me.source,
        'access_ends_at',me.access_ends_at,
        'coach_name',trim(coalesce(cp.first_name,'')||' '||coalesce(cp.last_name,'')),
        'last_workout_at',ps.last_completed_workout_at,
        'created_at',a.created_at
      ) order by a.created_at desc),'[]'::jsonb)
    ) into v_out
    from public.athletes a
    join public.profiles p on p.user_id=a.user_id
    left join public.athlete_program_state ps on ps.athlete_id=a.id
    left join lateral (
      select e.* from public.membership_entitlements e
      where e.user_id=a.user_id
      order by case when e.status in ('active','trialing','cancelled') and (e.access_ends_at is null or e.access_ends_at>now()) then 0 else 1 end,e.updated_at desc
      limit 1
    ) me on true
    left join lateral (
      select ca.coach_user_id from public.coach_assignments ca
      where ca.athlete_id=a.id and ca.status::text='active'
      order by ca.assigned_at desc limit 1
    ) ac on true
    left join public.profiles cp on cp.user_id=ac.coach_user_id;

  elsif v_section='revenue' then
    select jsonb_build_object(
      'generated_at',now(),
      'estimated_mrr_cents',
        coalesce((
          select sum(mp.monthly_price_cents)
          from public.billing_subscriptions b
          join public.membership_plans mp on mp.plan_code=b.plan_code
          where b.billing_type='individual'
            and b.status in ('active','trialing','cancel_at_period_end')
            and (b.current_period_end is null or b.current_period_end>now())
        ),0)
        +coalesce((
          select sum(greatest(p.requested_seats,0)*greatest(p.seat_price_cents,0))
          from public.coach_sponsorship_packages p
          where p.status in ('active','cancel_at_period_end')
            and (p.current_period_end is null or p.current_period_end>now())
        ),0),
      'subscriptions',coalesce((
        select jsonb_agg(jsonb_build_object(
          'audience',q.audience,'plan_code',q.plan_code,'provider',q.provider,'status',q.status,
          'billing_type',q.billing_type,'count',q.count,'base_mrr_cents',q.base_mrr_cents
        ) order by q.audience,q.plan_code,q.provider)
        from (
          select b.audience,b.plan_code,b.provider,b.status,b.billing_type,count(*) count,
                 sum(case when b.billing_type='individual' then coalesce(mp.monthly_price_cents,0) else 0 end) base_mrr_cents
          from public.billing_subscriptions b
          left join public.membership_plans mp on mp.plan_code=b.plan_code
          group by b.audience,b.plan_code,b.provider,b.status,b.billing_type
        ) q
      ),'[]'::jsonb),
      'sponsorship_mrr_cents',coalesce((
        select sum(greatest(p.requested_seats,0)*greatest(p.seat_price_cents,0))
        from public.coach_sponsorship_packages p
        where p.status in ('active','cancel_at_period_end')
      ),0),
      'pending_transitions',(select count(*) from public.billing_transitions t where t.status in ('requested','awaiting_payment','awaiting_provider','scheduled')),
      'recent_transitions',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',t.id,'audience',t.audience,'type',t.transition_type,'direction',t.direction,'status',t.status,
          'from_plan',t.from_plan_code,'to_plan',t.to_plan_code,'effective_at',t.effective_at,
          'expected_amount_cents',t.expected_amount_cents,'provider',t.provider,'created_at',t.created_at
        ) order by t.created_at desc)
        from (select * from public.billing_transitions order by created_at desc limit 50) t
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='sponsorships' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce(jsonb_agg(jsonb_build_object(
        'id',p.id,'coach_user_id',p.coach_user_id,
        'coach_name',trim(coalesce(pr.first_name,'')||' '||coalesce(pr.last_name,'')),
        'plan_code',p.plan_code,'requested_seats',p.requested_seats,'seat_price_cents',p.seat_price_cents,
        'status',p.status,'provider',p.provider,'period_end',p.current_period_end,
        'cancel_at_period_end',p.cancel_at_period_end,
        'available',coalesce(s.available,0),'invited',coalesce(s.invited,0),
        'active',coalesce(s.active,0),'scheduled_to_end',coalesce(s.scheduled_to_end,0),
        'updated_at',p.updated_at
      ) order by p.updated_at desc),'[]'::jsonb)
    ) into v_out
    from public.coach_sponsorship_packages p
    left join public.profiles pr on pr.user_id=p.coach_user_id
    left join lateral (
      select
        count(*) filter(where x.status='available') available,
        count(*) filter(where x.status='invited') invited,
        count(*) filter(where x.status in ('claimed','active')) active,
        count(*) filter(where x.status='scheduled_to_end') scheduled_to_end
      from public.coach_sponsor_seats x where x.package_id=p.id
    ) s on true;

  elsif v_section='organizations' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce(jsonb_agg(jsonb_build_object(
        'id',o.id,'name',o.name,'created_at',o.created_at,
        'members',coalesce(m.member_count,0),'teams',coalesce(t.team_count,0),
        'athletes',coalesce(a.athlete_count,0),'coaches',coalesce(c.coach_count,0)
      ) order by o.created_at desc),'[]'::jsonb)
    ) into v_out
    from public.organizations o
    left join lateral (select count(*) member_count from public.organization_members om where om.organization_id=o.id) m on true
    left join lateral (select count(*) team_count from public.teams tt where tt.organization_id=o.id) t on true
    left join lateral (
      select count(*) athlete_count
      from public.organization_members om join public.profiles p on p.user_id=om.user_id
      where om.organization_id=o.id and p.role::text='athlete'
    ) a on true
    left join lateral (
      select count(*) coach_count
      from public.organization_members om join public.profiles p on p.user_id=om.user_id
      where om.organization_id=o.id and p.role::text='coach'
    ) c on true;

  elsif v_section='support' then
    select jsonb_build_object(
      'generated_at',now(),
      'member_requests',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',s.id,'source','member','category',s.category,'status',s.status,'app_version',s.app_version,
          'created_at',s.created_at,'updated_at',s.updated_at,'user_id',s.user_id
        ) order by s.created_at desc)
        from (select * from public.support_requests order by created_at desc limit 100) s
      ),'[]'::jsonb),
      'public_requests',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',s.id,'source','public','category',s.category,'status',s.status,'app_version',s.app_version,
          'created_at',s.created_at,'updated_at',s.updated_at
        ) order by s.created_at desc)
        from (select * from public.public_support_requests order by created_at desc limit 100) s
      ),'[]'::jsonb),
      'deletion_requests',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',d.id,'user_id',d.user_id,'athlete_id',d.athlete_id,'status',d.status,
          'requested_at',d.requested_at,'completed_at',d.completed_at
        ) order by d.requested_at desc)
        from (select * from public.account_deletion_requests order by requested_at desc limit 100) d
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='website' then
    select jsonb_build_object(
      'generated_at',now(),
      'sessions_30d',(select count(distinct session_key) from public.founder_web_events where created_at>now()-interval '30 days'),
      'page_views_30d',(select count(*) from public.founder_web_events where event_type='page_view' and created_at>now()-interval '30 days'),
      'signup_starts_30d',(select count(*) from public.founder_web_events where event_type='signup_start' and created_at>now()-interval '30 days'),
      'checkout_starts_30d',(select count(*) from public.founder_web_events where event_type='checkout_start' and created_at>now()-interval '30 days'),
      'website_accounts_30d',(select count(*) from public.onboarding_journeys where channel='website' and created_at>now()-interval '30 days'),
      'website_paid_30d',(select count(*) from public.onboarding_journeys where channel='website' and payment_status in ('paid','active','confirmed') and created_at>now()-interval '30 days'),
      'top_pages',coalesce((
        select jsonb_agg(jsonb_build_object('page',q.page_path,'views',q.views,'sessions',q.sessions) order by q.views desc)
        from (
          select page_path,count(*) views,count(distinct session_key) sessions
          from public.founder_web_events
          where event_type='page_view' and created_at>now()-interval '30 days'
          group by page_path order by count(*) desc limit 20
        ) q
      ),'[]'::jsonb),
      'events',coalesce((
        select jsonb_agg(jsonb_build_object('event',q.event_type,'count',q.count) order by q.count desc)
        from (
          select event_type,count(*) count from public.founder_web_events
          where created_at>now()-interval '30 days'
          group by event_type
        ) q
      ),'[]'::jsonb),
      'onboarding_funnel',coalesce((
        select jsonb_agg(jsonb_build_object(
          'audience',q.audience,'stage',q.stage,'payment_status',q.payment_status,'count',q.count
        ) order by q.audience,q.stage)
        from (
          select audience,stage,payment_status,count(*) count
          from public.onboarding_journeys
          where channel='website' and created_at>now()-interval '90 days'
          group by audience,stage,payment_status
        ) q
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='marketing_sales' then
    select jsonb_build_object(
      'generated_at',now(),
      'pipeline_value_cents',(select coalesce(sum(estimated_monthly_value_cents),0) from public.founder_crm_leads where stage not in ('won','lost')),
      'won_value_cents',(select coalesce(sum(estimated_monthly_value_cents),0) from public.founder_crm_leads where stage='won'),
      'leads',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',l.id,'name',l.name,'organization',l.organization,'lead_type',l.lead_type,'stage',l.stage,
          'source',l.source,'assigned_agent_code',l.assigned_agent_code,
          'estimated_monthly_value_cents',l.estimated_monthly_value_cents,'next_action',l.next_action,
          'created_at',l.created_at,'updated_at',l.updated_at
        ) order by l.updated_at desc)
        from (select * from public.founder_crm_leads order by updated_at desc limit 100) l
      ),'[]'::jsonb),
      'campaigns',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',c.id,'name',c.name,'channel',c.channel,'status',c.status,'audience',c.audience,
          'objective',c.objective,'budget_cents',c.budget_cents,'spend_cents',c.spend_cents,
          'leads',c.leads,'conversions',c.conversions,'starts_at',c.starts_at,'ends_at',c.ends_at
        ) order by c.updated_at desc)
        from (select * from public.founder_marketing_campaigns order by updated_at desc limit 100) c
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='ai_company' then
    select jsonb_build_object(
      'generated_at',now(),
      'agents',coalesce((
        select jsonb_agg(jsonb_build_object(
          'code',a.code,'name',a.name,'title',a.title,'department',a.department,'manager_code',a.manager_code,
          'org_level',a.org_level,'mission',a.mission,'responsibilities',a.responsibilities,'kpis',a.kpis,
          'authority_level',a.authority_level,'status',a.status
        ) order by a.sort_order,a.department,a.title)
        from public.founder_ai_agents a where a.status<>'retired'
      ),'[]'::jsonb),
      'tasks',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',t.id,'agent_code',t.agent_code,'title',t.title,'description',t.description,'department',t.department,
          'priority',t.priority,'status',t.status,'requires_approval',t.requires_approval,'approval_status',t.approval_status,
          'output_summary',t.output_summary,'due_at',t.due_at,'created_at',t.created_at
        ) order by case t.priority when 'urgent' then 1 when 'high' then 2 when 'normal' then 3 else 4 end,t.created_at desc)
        from (select * from public.founder_ai_tasks where status not in ('cancelled') order by created_at desc limit 150) t
      ),'[]'::jsonb),
      'approvals',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',a.id,'category',a.category,'title',a.title,'description',a.description,'risk_level',a.risk_level,
          'status',a.status,'requested_by_agent_code',a.requested_by_agent_code,'created_at',a.created_at
        ) order by case a.risk_level when 'critical' then 1 when 'high' then 2 when 'medium' then 3 else 4 end,a.created_at desc)
        from (select * from public.founder_approvals where status='pending' order by created_at desc limit 100) a
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='knowledge' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',k.id,'title',k.title,'principle_text',k.principle_text,'structured_rule',k.structured_rule,
          'affected_areas',k.affected_areas,'conflict_notes',k.conflict_notes,'status',k.status,'version',k.version,
          'created_at',k.created_at,'updated_at',k.updated_at,'reviewed_at',k.reviewed_at,'published_at',k.published_at
        ) order by k.updated_at desc)
        from (select * from public.founder_knowledge_proposals order by updated_at desc limit 100) k
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='system' then
    select jsonb_build_object(
      'generated_at',now(),
      'billing_integrity',private.mw_billing_integrity_audit(),
      'diagnostics',jsonb_build_object(
        'errors_24h',(select count(*) from public.launch_diagnostics where severity='error' and created_at>now()-interval '24 hours'),
        'warnings_24h',(select count(*) from public.launch_diagnostics where severity='warn' and created_at>now()-interval '24 hours'),
        'events_24h',(select count(*) from public.launch_diagnostics where created_at>now()-interval '24 hours'),
        'latest',coalesce((
          select jsonb_agg(jsonb_build_object(
            'id',d.id,'surface',d.surface,'event_type',d.event_type,'severity',d.severity,'code',d.code,
            'route',d.route,'app_version',d.app_version,'ios_build',d.ios_build,'platform',d.platform,
            'online',d.online,'created_at',d.created_at
          ) order by d.created_at desc)
          from (select * from public.launch_diagnostics order by created_at desc limit 80) d
        ),'[]'::jsonb)
      ),
      'pending_billing_transitions',(select count(*) from public.billing_transitions where status in ('requested','awaiting_payment','awaiting_provider','scheduled')),
      'app_version','3.0.16',
      'ios_build','13'
    ) into v_out;

  elsif v_section='audit' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',a.id,'actor_user_id',a.actor_user_id,'actor_role',a.actor_role::text,'action',a.action,
          'target_type',a.target_type,'target_id',a.target_id,'reason',a.reason,'created_at',a.created_at
        ) order by a.created_at desc)
        from (select * from public.audit_log order by created_at desc limit 150) a
      ),'[]'::jsonb)
    ) into v_out;

  elsif v_section='applications' then
    select jsonb_build_object(
      'generated_at',now(),
      'items',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',a.id,'first_name',a.first_name,'last_name',a.last_name,'organization',a.organization,
          'coach_title',a.coach_title,'coaching_level',a.coaching_level,'years_coaching',a.years_coaching,
          'athlete_count',a.athlete_count,'status',a.status,'verification_status',a.verification_status,
          'decision_mode',a.decision_mode,'decision_reason',a.decision_reason,'verification_method',a.verification_method,
          'verification_detail',a.verification_detail,'verification_evidence',a.verification_evidence,
          'payment_status',a.payment_status,'selected_plan_code',a.selected_plan_code,
          'sponsored_athlete_seats',a.sponsored_athlete_seats,'created_at',a.created_at,'updated_at',a.updated_at
        ) order by a.created_at desc)
        from (select * from public.coach_access_applications order by created_at desc limit 150) a
      ),'[]'::jsonb)
    ) into v_out;

  else
    raise exception 'Unknown Founder OS section: %',v_section using errcode='22023';
  end if;

  return coalesce(v_out,'{}'::jsonb);
end $function$
;

CREATE OR REPLACE FUNCTION public.mw_record_web_event(p_session_key text, p_event_type text, p_page_path text, p_audience text DEFAULT NULL::text, p_source text DEFAULT NULL::text, p_campaign text DEFAULT NULL::text, p_referrer_host text DEFAULT NULL::text, p_device_class text DEFAULT NULL::text, p_metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_event text := lower(left(trim(coalesce(p_event_type,'')),50));
  v_page text := left(split_part(split_part(coalesce(p_page_path,'/'),'? ',1),'#',1),160);
  v_session text := left(regexp_replace(coalesce(p_session_key,''),'[^a-zA-Z0-9_-]','','g'),80);
begin
  v_page := left(split_part(split_part(coalesce(p_page_path,'/'),'?',1),'#',1),160);
  if v_event not in ('page_view','cta_click','role_choice','signup_start','signup_complete','checkout_start','support_open','app_open') then return false; end if;
  if length(v_session) < 8 then return false; end if;
  if v_page='' then v_page:='/'; end if;
  if exists(
    select 1 from public.founder_web_events
    where session_key=v_session and event_type=v_event and page_path=v_page
      and created_at > now()-interval '8 seconds'
  ) then return true; end if;
  insert into public.founder_web_events(
    session_key,user_id,event_type,page_path,audience,source,campaign,referrer_host,device_class,metadata
  ) values (
    v_session,auth.uid(),v_event,v_page,
    nullif(left(trim(coalesce(p_audience,'')),40),''),
    nullif(left(trim(coalesce(p_source,'')),80),''),
    nullif(left(trim(coalesce(p_campaign,'')),80),''),
    nullif(left(trim(coalesce(p_referrer_host,'')),120),''),
    nullif(left(trim(coalesce(p_device_class,'')),30),''),
    case when jsonb_typeof(coalesce(p_metadata,'{}'::jsonb))='object'
      then coalesce(p_metadata,'{}'::jsonb)-'email'-'name'-'message'-'token'-'password'
      else '{}'::jsonb end
  );
  return true;
end $function$
;

revoke all on function public.mw_record_web_event(text,text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.mw_record_web_event(text,text,text,text,text,text,text,text,jsonb) to anon,authenticated;
revoke all on function public.mw_founder_os_snapshot(text) from public;
grant execute on function public.mw_founder_os_snapshot(text) to authenticated;
