create table if not exists public.launch_diagnostics (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  surface text not null check (surface in ('athlete','coach','account','native','unknown')),
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warn','error')),
  code text,
  route text,
  app_version text,
  ios_build text,
  platform text,
  online boolean,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.launch_diagnostics enable row level security;

drop policy if exists mw_launch_diagnostics_insert_own on public.launch_diagnostics;
create policy mw_launch_diagnostics_insert_own
on public.launch_diagnostics
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists mw_launch_diagnostics_select_own on public.launch_diagnostics;
create policy mw_launch_diagnostics_select_own
on public.launch_diagnostics
for select
to authenticated
using (user_id = auth.uid());

create index if not exists launch_diagnostics_user_created_idx
  on public.launch_diagnostics(user_id, created_at desc);

create index if not exists launch_diagnostics_event_created_idx
  on public.launch_diagnostics(event_type, created_at desc);

comment on table public.launch_diagnostics is
'Non-sensitive MW Dynasty launch diagnostics. No tokens, request bodies, emails, message content, or payment credentials.';
